### ISSUE TITLE
Bug: MessageKit Wallets fail in Converse import key

### ISSUE THREAD

**Issue by humanagent** [ephemeraHQ/message-kit#125]
[Bug: MessageKit Wallets fail in Converse import key](https://github.com/xmtp/xmtp-react-native/issues/512)

**Comment by fabriguespe** [comment]
Debugged step by step and the thing that breaks the import in messagekit is this line

`await client.registerIdentity();`

**Comment by humanagent** [comment]
https://github.com/ephemeraHQ/message-kit/pull/128
Fixed with latest node-sdk!
